[package]
name = "mash-tui"
edition.workspace = true
version.workspace = true

[[bin]]
name = "mash"
path = "src/main.rs"

[dependencies]
mashd = { path = "../mashd" }
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
dirs.workspace = true
iocraft.workspace = true
serde_json.workspace = true
tokio.workspace = true
